{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
spec:
  to:
    kind: Service
    name: {{ .Chart.Name }}
  port:
    targetPort: 8080
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: edge
  {{- end }}
{{- end }}

