apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomiz-prod-env
resources:
  - ../../base

labels:
  - pairs:
      env: prod
patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: webapp-kustomize
    options:
      allowNameChange: true